### ISSUE TITLE
two-image css rule not in main.css in production

### ISSUE THREAD

**Issue by cyrneko** [tedgravlin/signal-update-info#6]
navigating to https://signalupdateinfo.com/news/chat-folders.html I noticed that the images are not scaled nor placed correctly, and with their border missing. Upon searching in the `main.css` as it's served in production, for some reason the following CSS rules are nowhere to be found:
```css

div.two-image {
    display: grid;
    width: fit-content;
    grid-template-columns: 1fr 1fr;
    margin: 1em auto 1em auto;
    column-gap: 1em;
    row-gap: 1em;
}

div.two-image > img {
    width: 30vw;
    border-radius: 24px;
    border: 2px solid var(--text-color);
}

/* Later in the file ↓ */
/* In @media (max-width...) */
div.two-image {
    grid-template-columns: 1fr;
}

div.two-image > img {
    width: 100%;
}

```

Is there something wrong with the GitHub Actions / Pages runner? Maybe it should be manually ran again just in case?

I could not replicate this locally (see image)

![image](https://github.com/user-attachments/assets/24c96b20-fb98-419a-9a1d-53c008ffe7bd)
> Left is signalupdatesinfo.com, right is locally-served copy of `HEAD`
